name: Build and Upload

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Automatyczne uruchamianie co tydzień
  workflow_dispatch: # Ręczne uruchamianie przez użytkownika

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install PyQt5
        pip install pyyaml

    - name: Build executable
      run: pyinstaller --onefile --noconsole project.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/project.exe
